default['test_2']['name'] = 'test_2'
default['test_2']['channel'] = ''
default['test_2']['install_version'] = ''
default['test_2']['chef_server_name'] = ''
default['test_2']['jq_url'] = 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
